// Mirrors the Postgres enum types created in db/migrations/0001_init.sql.
// Previously these were generated by `@prisma/client`.

export type TenantStatus = 'PENDING' | 'LIVE' | 'SUSPENDED';
export const TenantStatus = {
  PENDING: 'PENDING' as TenantStatus,
  LIVE: 'LIVE' as TenantStatus,
  SUSPENDED: 'SUSPENDED' as TenantStatus,
};

export type ProjectStatus = 'LATEST' | 'ONGOING' | 'COMPLETED';
export const ProjectStatus = {
  LATEST: 'LATEST' as ProjectStatus,
  ONGOING: 'ONGOING' as ProjectStatus,
  COMPLETED: 'COMPLETED' as ProjectStatus,
};

export type FieldType =
  | 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'IMAGE' | 'IMAGE_MULTI'
  | 'FILE' | 'CHECKBOX' | 'LOCATION' | 'PRICE' | 'AREA' | 'DATERANGE';
export const FieldType = {
  TEXT: 'TEXT' as FieldType,
  NUMBER: 'NUMBER' as FieldType,
  SELECT: 'SELECT' as FieldType,
  MULTISELECT: 'MULTISELECT' as FieldType,
  IMAGE: 'IMAGE' as FieldType,
  IMAGE_MULTI: 'IMAGE_MULTI' as FieldType,
  FILE: 'FILE' as FieldType,
  CHECKBOX: 'CHECKBOX' as FieldType,
  LOCATION: 'LOCATION' as FieldType,
  PRICE: 'PRICE' as FieldType,
  AREA: 'AREA' as FieldType,
  DATERANGE: 'DATERANGE' as FieldType,
};

export interface TenantField {
  id: number;
  tenantId: number;
  key: string;
  label: string;
  type: FieldType;
  section: string;
  order: number;
  required: boolean;
  placeholder: string | null;
  options: unknown;
  validation: unknown;
  showInList: boolean;
  maxLength: number | null;
  imageWidth: number | null;
  imageHeight: number | null;
  allowCaption: boolean;
}
